import { pgTable, uuid, varchar, text, timestamp, boolean, jsonb, index } from "drizzle-orm/pg-core";
import { emailThreads } from "./email-threads";
import { companies } from "./companies";
import { contacts } from "./contacts";

export const emailMessages = pgTable(
  "email_messages",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    threadId: uuid("thread_id").references(() => emailThreads.id, { onDelete: "set null" }),
    companyId: uuid("company_id").references(() => companies.id, { onDelete: "set null" }),
    contactId: uuid("contact_id").references(() => contacts.id, { onDelete: "set null" }),
    providerMessageId: varchar("provider_message_id", { length: 500 }).unique(),
    direction: varchar("direction", { length: 10 }).notNull(),
    fromAddress: varchar("from_address", { length: 255 }).notNull(),
    toAddresses: jsonb("to_addresses").$type<string[]>().notNull(),
    subject: text("subject"),
    bodyText: text("body_text"),
    bodyHtml: text("body_html"),
    receivedAt: timestamp("received_at", { withTimezone: true }).notNull(),
    isAutoGenerated: boolean("is_auto_generated").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("idx_messages_thread").on(table.threadId),
    index("idx_messages_company").on(table.companyId),
    index("idx_messages_contact").on(table.contactId),
    index("idx_messages_provider_id").on(table.providerMessageId),
    index("idx_messages_received").on(table.receivedAt),
    index("idx_messages_direction").on(table.direction),
  ]
);

export type EmailMessage = typeof emailMessages.$inferSelect;
export type NewEmailMessage = typeof emailMessages.$inferInsert;
